// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCf8hVy_dvrVDrMlwFWVFuGpdB730RSit4',
    appId: '1:651963948857:web:9ada7de37e4302096392e8',
    messagingSenderId: '651963948857',
    projectId: 'chat-app-7f34b',
    authDomain: 'chat-app-7f34b.firebaseapp.com',
    storageBucket: 'chat-app-7f34b.appspot.com',
    measurementId: 'G-4RGJN2TQBE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLmRU8rY9Jo9zJRhsd0IOtH46EPpWvBGE',
    appId: '1:651963948857:android:353d42cf8ad629e16392e8',
    messagingSenderId: '651963948857',
    projectId: 'chat-app-7f34b',
    storageBucket: 'chat-app-7f34b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9nf2bzK-J_wh3V8fse9AGMiZ9GnXmMpg',
    appId: '1:651963948857:ios:af4d51d0b7d2c7226392e8',
    messagingSenderId: '651963948857',
    projectId: 'chat-app-7f34b',
    storageBucket: 'chat-app-7f34b.appspot.com',
    iosBundleId: 'com.example.scholarChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9nf2bzK-J_wh3V8fse9AGMiZ9GnXmMpg',
    appId: '1:651963948857:ios:9830e23b347667e06392e8',
    messagingSenderId: '651963948857',
    projectId: 'chat-app-7f34b',
    storageBucket: 'chat-app-7f34b.appspot.com',
    iosBundleId: 'com.example.scholarChat.RunnerTests',
  );
}
